# Generated by Django 5.0.6 on 2024-07-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_rename_units_per_case_product_units_per_qty_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="created",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
